### ISSUE TITLE
How do i use this to bypass the 10000 limit on cloudwatch insight?

### ISSUE THREAD

**Issue by ryanoolala** [gogama/incite#22]
I tried reading the readme, but i am not sure what settings i should use.

I tried SplitUntil, but it requires limit, and there is still the MaxLimit that is a constant at 10000, how do i bypass this MaxLimit?

**Comment by vcschapp** [comment]
The setting you need to use is a field in the [`QuerySpec`](https://pkg.go.dev/github.com/gogama/incite#QuerySpec) called `Chunk`. 

- Setting `Chunk` tells Incite to break your query time range up into many smaller queries of size `Chunk`.
- The `Limit` field applies to each chunk individually. This allows you to work around the CloudWatch Logs Insights 10K result limit and get unlimited results.
- Incite will handle all the chunks transparently. You just need to read the results out of the stream!
- You still need to set a value of `Chunk` that is small enough so each chunk doesn't overflow the 10K results limit. This is where `SplitUntil` comes in handy, because if you turn on `Chunk` *and* `SplitUntil` then Incite will recursively sub-divide chunks that get too many results into smaller chunks.

**Comment by vcschapp** [comment]
I tried to improve the documentation a bit to help make it more obvious what to do.

Let me know if you're able to get it working!

**Comment by ryanoolala** [comment]
Hmm thanks for the suggestions, i'm still stuck at getting a right config, maybe if you can show what are the right values you would configure for an example like this will help.

I will like to query across 2022-09-01 to 2022-09-20, YYYY-MM-DD. 
I expect to have around 100000 to 200000 results (way above the 10k max limit)

How would i write a queryspec for such a case?

**Comment by vcschapp** [comment]
```go
s, err := m.Query(
		Text:   "<YOUR QUERY TEXT HERE>",
		Start:  time.Date(2022, 9, 1, 0, 0, 0, 0, nil),
		End:    time.Date(2022, 9, 21, 0, 0, 0, 0, nil),
		Groups: []string{"YOUR LOG GROUP(S) HERE"},
		Limit:  incite.MaxLimit,
		Chunk: 12*time.Hour,
)
```go

**Comment by vcschapp** [comment]
@ryanoolala Did that help, or could you let me know what other problem's you're having?

**Comment by ryanoolala** [comment]
Thanks! that worked.

My issue was on the calculation of the chunk, was using some random whole numbers and didn't understand what was happening.

**Comment by vcschapp** [comment]
Great! I'm glad it's working for you!

I'm going to close this based on your indication that it's resolved, but please don't hesitate to open another issue if you have another question.
